#!/usr/bin/env python3
"""Bundle cat.lua + its 6 _load_module dependencies into a single catmio.lua."""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

with open(REPO / "cat.lua", "r", encoding="utf-8") as f:
    cat_src = f.read()

def read_module(name):
    return (REPO / name).read_text(encoding="utf-8")

# Map each _load_module(...) line to its replacement.
# We use a regex per call so we can preserve any `local x = ` left-hand side.
# Each replacement wraps the inlined content in an IIFE so the module's
# top-level `return ...` keeps working, OR a do...end if there's no return.

def banner(name):
    bar = "-- " + ("=" * 76)
    return f"\n{bar}\n-- BEGIN INLINED MODULE: {name}\n{bar}\n"

def end_banner(name):
    bar = "-- " + ("=" * 76)
    return f"{bar}\n-- END INLINED MODULE: {name}\n{bar}\n"

def replace_one(haystack, lhs_pattern, module_name, has_return):
    src = read_module(module_name)
    if has_return:
        # Wrap in immediately-invoked function so return works.
        replacement = (
            banner(module_name)
            + lhs_pattern
            + " = (function()\n"
            + src.rstrip("\n")
            + "\nend)()\n"
            + end_banner(module_name)
        )
    else:
        # Wrap in do...end. The void modules write to _CATMIO.q so locals
        # don't need to escape.
        replacement = (
            banner(module_name)
            + "do\n"
            + src.rstrip("\n")
            + "\nend\n"
            + end_banner(module_name)
        )
    return replacement

# Sequential replacements (use specific patterns to avoid mismatches).
replacements = [
    # cat_config.lua: returns (r, BLOCKED_OUTPUT_PATTERNS)
    (
        r'local r, BLOCKED_OUTPUT_PATTERNS = _load_module\("cat_config\.lua"\)',
        "local r, BLOCKED_OUTPUT_PATTERNS",
        "cat_config.lua",
        True,
    ),
    # cat_stubs.lua: returns (exploit_funcs, _collect_gc_objects)
    (
        r'local exploit_funcs, _collect_gc_objects = _load_module\("cat_stubs\.lua"\)',
        "local exploit_funcs, _collect_gc_objects",
        "cat_stubs.lua",
        True,
    ),
    # cat_bit.lua: returns the bit lib
    (
        r'local _bit\s*=\s*_load_module\("cat_bit\.lua"\)',
        "local _bit",
        "cat_bit.lua",
        True,
    ),
    # cat_envlogger.lua: void
    (
        r'_load_module\("cat_envlogger\.lua"\)',
        None,
        "cat_envlogger.lua",
        False,
    ),
    # cat_deobf.lua: returns _deobf
    (
        r'local _deobf = _load_module\("cat_deobf\.lua"\)',
        "local _deobf",
        "cat_deobf.lua",
        True,
    ),
    # cat_sandbox.lua: void
    (
        r'_load_module\("cat_sandbox\.lua"\)',
        None,
        "cat_sandbox.lua",
        False,
    ),
]

out = cat_src
for pat, lhs, module, has_return in replacements:
    repl = replace_one(out, lhs, module, has_return)
    new_out, n = re.subn(pat, lambda m: repl, out, count=1)
    if n != 1:
        raise SystemExit(f"FAILED to find pattern for {module}: {pat!r}")
    out = new_out

# Front-matter banner.
header = """-- catmio.lua
-- ============================================================================
-- Catmio: single-file bundle of the entire deobfuscation engine.
--
-- This file is generated by inlining the 7 modules of the catmio project
-- into a single self-contained Lua chunk:
--
--   cat_config.lua     ->  configuration + BLOCKED_OUTPUT_PATTERNS
--   cat_bit.lua        ->  portable bitwise library (Lua 5.1 compatible)
--   cat_stubs.lua      ->  exploit-executor function stubs
--   cat_deobf.lua      ->  static deobfuscator / string-pool extractor
--   cat_envlogger.lua  ->  output / dump layer (envlogger v3)
--   cat_sandbox.lua    ->  sandbox execution + entry points
--   cat.lua            ->  glue + Roblox proxy + main loop
--
-- Run as:
--   lua catmio.lua <input.lua> [output.lua]
--
-- The original modular files remain in this repo unchanged; this bundle is
-- a separate distribution-friendly artifact. All public APIs (q.dump_*,
-- q.envlogger_*, etc.) are preserved.
-- ============================================================================

"""

# Write output.
output_path = REPO / "catmio.lua"
output_path.write_text(header + out, encoding="utf-8")

# Stats.
print(f"Wrote {output_path}")
print(f"Lines: {len(output_path.read_text(encoding='utf-8').splitlines())}")
